// Committed CRC table of the scene goldens (generated by `qz_golden --update`).
#include "qz/selftest/selftest.hpp"

#include <array>

namespace qz::selftest {

namespace {

constexpr auto kGoldenCrcs = std::to_array<GoldenCrc>({
#include "golden_crc.inc"
});

} // namespace

std::span<const GoldenCrc> golden_crcs() noexcept {
    return kGoldenCrcs;
}

} // namespace qz::selftest
