// gfx::font(): the compiled-in fonts. The data is generated by tools/fontgen.py from the Spleen BDF
// sources (src/generated/fonts_data.hpp, committed; `python3 tools/fontgen.py --check` verifies
// it).
#include "generated/fonts_data.hpp"
#include "qz/gfx/framebuffer.hpp"

#include <cstddef>

namespace qz::gfx {

static_assert(std::size(generated::kFonts) == static_cast<std::size_t>(FontId::kCount),
              "one generated font per FontId");

const Font& font(FontId id) noexcept {
    auto index = static_cast<std::size_t>(id);
    if (index >= std::size(generated::kFonts)) {
        index = static_cast<std::size_t>(FontId::kSmall); // fail safe: an unknown id still renders
    }
    return generated::kFonts[index];
}

} // namespace qz::gfx
