// Golden-image machinery shared by the qz_golden tool and the qz_selftest host tests
// (header-only, host only). A golden is the deterministic PNG of one canonical scene.
#pragma once

#include "qz/core/crc32.hpp"
#include "qz/faces/registry.hpp"
#include "qz/gfx/framebuffer.hpp"
#include "qz/selftest/selftest.hpp"

#include <algorithm>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

namespace qz::golden {

namespace fs = std::filesystem;

using Bytes = std::vector<std::uint8_t>;

class VectorSink final : public gfx::ByteSink {
public:
    Status write(std::span<const std::uint8_t> bytes) override {
        data.insert(data.end(), bytes.begin(), bytes.end());
        return ok();
    }
    Bytes data;
};

/// Renders the scene exactly as the device does. Empty optional on a render error.
inline std::optional<gfx::Framebuffer> render(const selftest::Scene& scene,
                                              const ui::FaceSource& faces) {
    gfx::Framebuffer fb;
    if (!selftest::render_scene(scene, faces, fb)) {
        return std::nullopt;
    }
    return fb;
}

inline std::optional<Bytes> encode(const gfx::Framebuffer& fb) {
    VectorSink sink;
    if (!gfx::encode_png(fb, sink)) {
        return std::nullopt;
    }
    return std::move(sink.data);
}

inline std::optional<Bytes> read_file(const fs::path& path) {
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        return std::nullopt;
    }
    return Bytes(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
}

inline bool write_file(const fs::path& path, std::span<const std::uint8_t> bytes) {
    std::error_code ec;
    fs::create_directories(path.parent_path(), ec);
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    out.write(reinterpret_cast<const char*>(bytes.data()),
              static_cast<std::streamsize>(bytes.size()));
    return static_cast<bool>(out);
}

inline bool write_text(const fs::path& path, const std::string& text) {
    return write_file(path, {reinterpret_cast<const std::uint8_t*>(text.data()), text.size()});
}

/// Reads a PNG produced by gfx::encode_png back into a framebuffer. The encoder's layout is
/// fixed (stored deflate blocks, filter 0, 26-byte rows), so the header of a blank frame is
/// the reference; anything else yields nullopt.
inline std::optional<gfx::Framebuffer> decode(std::span<const std::uint8_t> png) {
    const gfx::Framebuffer blank;
    const std::optional<Bytes> ref = encode(blank);
    constexpr std::size_t kRow = gfx::kStride + 1U;
    if (!ref || png.size() != ref->size()) {
        return std::nullopt;
    }
    const std::size_t pixels_at =
        ref->size() - 12U /*IEND*/ - 4U /*adler*/ - (kRow * gfx::kHeight) - 4U /*IDAT crc*/;
    if (pixels_at > ref->size() ||
        !std::equal(
            ref->begin(), ref->begin() + static_cast<std::ptrdiff_t>(pixels_at), png.begin())) {
        return std::nullopt;
    }
    gfx::Framebuffer fb;
    for (std::size_t y = 0; y < static_cast<std::size_t>(gfx::kHeight); ++y) {
        for (std::size_t x = 0; x < gfx::kStride; ++x) {
            // PNG 1-bit grayscale: black = 0; framebuffer: black ink = 1.
            fb.bits[(y * gfx::kStride) + x] =
                static_cast<std::uint8_t>(~png[pixels_at + (y * kRow) + 1U + x]);
        }
    }
    return fb;
}

inline std::uint32_t diff_pixels(const gfx::Framebuffer& a, const gfx::Framebuffer& b) {
    std::uint32_t n = 0;
    for (std::int16_t y = 0; y < gfx::kHeight; ++y) {
        for (std::int16_t x = 0; x < gfx::kWidth; ++x) {
            n += a.get(x, y) != b.get(x, y) ? 1U : 0U;
        }
    }
    return n;
}

/// Black where the two frames differ.
inline gfx::Framebuffer diff_image(const gfx::Framebuffer& a, const gfx::Framebuffer& b) {
    gfx::Framebuffer d;
    for (std::int16_t y = 0; y < gfx::kHeight; ++y) {
        for (std::int16_t x = 0; x < gfx::kWidth; ++x) {
            if (a.get(x, y) != b.get(x, y)) {
                d.set(x, y, gfx::Color::kBlack);
            }
        }
    }
    return d;
}

inline fs::path png_path(const fs::path& golden_dir, std::string_view scene) {
    return golden_dir / (std::string(scene) + ".png");
}

/// Content of src/golden_crc.inc for the current renderer output.
inline std::optional<std::string> crc_table_text(const ui::FaceSource& faces) {
    std::string text =
        "// Generated by `qz_golden --update` (host/golden). Do not edit by hand.\n"
        "// {scene, CRC-32 of the 5000-byte framebuffer = gfx::Framebuffer::crc32()}\n";
    for (const selftest::Scene& scene : selftest::scenes()) {
        const std::optional<gfx::Framebuffer> fb = render(scene, faces);
        if (!fb) {
            return std::nullopt;
        }
        constexpr std::string_view kHex = "0123456789ABCDEF";
        std::string hex;
        const std::uint32_t crc = fb->crc32();
        for (int shift = 28; shift >= 0; shift -= 4) {
            hex.push_back(kHex[(crc >> static_cast<unsigned>(shift)) & 0xFU]);
        }
        text += "{\"" + std::string(scene.name) + "\", 0x" + hex + "U},\n";
    }
    return text;
}

struct SceneCheck {
    bool ok = false;
    std::uint32_t diff_pixels = 0;
    std::string message; ///< human-readable reason when !ok
};

/// Compares one scene with its committed PNG byte for byte. On mismatch writes
/// <out_dir>/<scene>.actual.png and <scene>.diff.png (black = differing pixel) when out_dir is set.
inline SceneCheck check_scene(const selftest::Scene& scene,
                              const ui::FaceSource& faces,
                              const fs::path& golden_dir,
                              const fs::path& out_dir) {
    SceneCheck r;
    const std::optional<gfx::Framebuffer> actual = render(scene, faces);
    if (!actual) {
        r.message = "render failed";
        return r;
    }
    const std::optional<Bytes> actual_png = encode(*actual);
    const std::optional<Bytes> golden_png = read_file(png_path(golden_dir, scene.name));
    if (!actual_png) {
        r.message = "png encode failed";
        return r;
    }
    if (!golden_png) {
        r.message = "golden missing (run qz_golden --update)";
        return r;
    }
    if (*golden_png == *actual_png) {
        r.ok = true;
        return r;
    }
    const std::optional<gfx::Framebuffer> expected = decode(*golden_png);
    r.message = "PNG differs from golden";
    if (expected) {
        r.diff_pixels = diff_pixels(*actual, *expected);
        r.message += ": " + std::to_string(r.diff_pixels) + " pixel(s) differ";
    } else {
        r.message += " (golden is not a Quartz PNG; pixel diff unavailable)";
    }
    if (!out_dir.empty()) {
        (void)write_file(out_dir / (std::string(scene.name) + ".actual.png"), *actual_png);
        if (expected) {
            if (const std::optional<Bytes> diff = encode(diff_image(*actual, *expected))) {
                (void)write_file(out_dir / (std::string(scene.name) + ".diff.png"), *diff);
            }
        }
        r.message += "; wrote " + (out_dir / (std::string(scene.name) + ".actual.png")).string();
    }
    return r;
}

/// PNG files in golden_dir that belong to no scene.
inline std::vector<std::string> orphan_goldens(const fs::path& golden_dir) {
    std::vector<std::string> orphans;
    std::error_code ec;
    for (const fs::directory_entry& e : fs::directory_iterator(golden_dir, ec)) {
        if (e.path().extension() != ".png") {
            continue;
        }
        const std::string stem = e.path().stem().string();
        const auto all = selftest::scenes();
        if (std::none_of(
                all.begin(), all.end(), [&](const selftest::Scene& s) { return s.name == stem; })) {
            orphans.push_back(e.path().filename().string());
        }
    }
    std::sort(orphans.begin(), orphans.end());
    return orphans;
}

} // namespace qz::golden
