// Built-in zone database (ARCHITECTURE.md section 9). The table itself is generated by
// tools/tzgen.py from a pinned IANA tzdata release and committed as tz_table.inc; this file only
// exposes it. The table is constant data: no heap, no locks, safe from any task.
#include "qz/time/tz.hpp"

#include <array>
#include <span>
#include <string_view>

namespace qz::time {
namespace {

#include "tz_table.inc"

} // namespace

std::span<const TzEntry> builtin_zones() noexcept {
    return kZoneTable;
}

const TzEntry* find_zone(std::string_view iana_name) noexcept {
    for (const TzEntry& zone : kZoneTable) {
        if (zone.name == iana_name) {
            return &zone;
        }
    }
    return nullptr;
}

std::string_view tzdata_version() noexcept {
    return kTzdataVersion;
}

} // namespace qz::time
